export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

export const INITIAL_AUTH = "INITIAL_AUTH";

export const PROCESS_FETCH = "PROCESS_FETCH";
export const PROCESS_SUCCESS = "PROCESS_SUCCESS";
export const PROCESS_FAILURE = "PROCESS_FAILURE";