export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

export const ACTIVATION_FETCH = "ACTIVATION_FETCH";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAILURE = "ACTIVATION_FAILURE";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";