export const CHAPTER_FETCH = "CHAPTER_FETCH";
export const CHAPTER_SUCCESS = "CHAPTER_SUCCESS";
export const CHAPTER_FAILURE = "CHAPTER_FAILURE";
export const TOGGLE_CHAPTER_LIKE = "TOGGLE_CHAPTER_LIKE";
export const CHAPTER_DELETED = "CHAPTER_DELETED";
export const REMOVE_CHAPTER = "REMOVE_CHAPTER";