export const FANFIC_FETCH = "FANFIC_FETCH";
export const FANFIC_SUCCESS = "FANFIC_SUCCESS";
export const FANFIC_FAILURE = "FANFIC_FAILURE";
export const FANFIC_TOGGLE_FAVORITE = "FANFIC_TOGGLE_FAVORITE";
export const FANFIC_SET_RATE = "FANFIC_SET_RATE";
export const FANFIC_DELETED = "FANFIC_DELETED";
export const REMOVE_FANFIC = "REMOVE_FANFIC";