export const PROFILE_FETCH = "PROFILE_FETCH";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";

export const PROFILE_FANFICS_FETCH = "PROFILE_FANFICS_FETCH";
export const PROFILE_FANFICS_SUCCESS = "PROFILE_FANFICS_SUCCESS";
export const PROFILE_FANFICS_FAILURE = "PROFILE_FANFICS_FAILURE";