export const PROFILE_FETCH = "PROFILE_FETCH";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";
export const PROFILE_DELETED = "PROFILE_DELETED";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
