export const USER_FETCH = "USER_FETCH";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const REMOVE_USER = "REMOVE_USER";
export const ACTIVATED = "ACTIVATED";
export const INITIALIZEDPREFERENCES = "INITIALIZEDPREFERENCES";
